First pass integrating component spec - stubs complete.
GANdy-team/GANdy pull request #3
Opened 2021-02-27 00:44 UTC by EvanKomp

2021-02-27 00:49 UTC, EvanKomp commented on gandy/models/models.py
> +        #. assert inputs
Is this needed with typing?

2021-02-27 00:53 UTC, EvanKomp commented on gandy/models/models.py
> +              session: str = None,
add metric keyword argument

2021-02-27 00:57 UTC, EvanKomp commented on gandy/models/models.py
> +              metric: Union[str, Callable],
give a default value later

2021-02-27 00:58 UTC, EvanKomp commented on gandy/models/models.py
> +        #. predictions, uncertainties = execute self.predict on Xs
_predict, not predict

2021-02-27 01:00 UTC, EvanKomp commented on gandy/models/models.py
> +        return cost, costs
call loss. metric_value and metric_values instead

2021-02-27 01:03 UTC, EvanKomp commented on gandy/models/models.py
> +    def save(self,
Can we make this a child defined method instead eg. predict. Raise not implemented in parent

2021-02-27 01:08 UTC, EvanKomp commented on gandy/models/models.py
> +        ## test new shape, delete model
where is the definition

2021-02-27 01:10 UTC, EvanKomp commented on gandy/models/models.py
> +        ## test new shape, delete model
dude define the method

2021-02-27 01:32 UTC, EvanKomp reviewed
I can't request changes but you should make them...

2021-02-27 01:32 UTC, EvanKomp commented on gandy/models/hypersearch.py
> +Model = Type[import gandy.models.models.UncertaintyModel]
import?

2021-02-27 01:32 UTC, EvanKomp commented on gandy/models/hypersearch.py
> +        return score
score makes it seem good but we are trying to minimize, loss?

2021-02-27 01:32 UTC, EvanKomp commented on gandy/models/hypersearch.py
> +        return single_score
loss not score

2021-02-27 01:32 UTC, EvanKomp commented on gandy/models/hypersearch.py
> +    @search_space.setter(self, new_search_space):
define the method

2021-02-27 01:44 UTC, EvanKomp commented on gandy/quality_est/metrics.py
> +    ''' Method that defines the mathematical formula necessary to compute the RMSE.
Docstring not correct

2021-02-27 01:49 UTC, EvanKomp reviewed
Nice work kyle, a few functional things.

2021-02-27 01:49 UTC, EvanKomp commented on gandy/quality_est/metrics.py
> +
call calculate in init

2021-02-27 01:49 UTC, EvanKomp commented on gandy/quality_est/metrics.py
> +
add a calculate method to parent that does nothing

2021-02-27 01:49 UTC, EvanKomp commented on gandy/quality_est/metrics.py
> +    return MSE_value
save the value insead of returning maybe

2021-02-27 01:49 UTC, EvanKomp commented on gandy/quality_est/metrics.py
> +## imports
add a docstring to the module

2021-02-27 01:58 UTC, EvanKomp commented on gandy/models/gans.py
> +        return None
return model for self.build

2021-02-27 02:00 UTC, stetef requested changes
Make appropriate changes (see comments)

2021-02-27 02:00 UTC, stetef commented on gandy/models/bnns.py
> +    def create_model_inputs(self, feature_names):
Added typing

2021-03-02 02:00 UTC, stetef approved these changes

2021-03-02 02:04 UTC, kmosko approved these changes
Changes look good!

2021-03-02 02:04 UTC, kmosko commented on gandy/quality_est/metrics.py
> +    def calculate(**kwargs):
Add self keyword to methods within metric children classes

2021-03-02 02:04 UTC, kmosko commented on gandy/quality_est/metrics.py
> +
Return final metric value and list of individual metrics for each prediction

2021-03-02 02:04 UTC, kmosko commented on gandy/quality_est/metrics.py
> +    return
Adjust tab for return statements

2021-03-02 02:05 UTC, merged